### ISSUE TITLE
DAP Debug not working

### ISSUE THREAD

**Issue by rag-hav** [alfaix/neotest-gtest#21]
Hey,

The debug adapter was not working for me. I looked around and adding 

`    cwd =utils.normalized_root(vim.loop.cwd()),
`

to the table returned by NeotestAdapter:_build_spec_for_executable in file `lua/neotest-gtest/neotest_adapter.lua` fixed it.

**Comment by alfaix** [comment]
Hey, thank you for contributing, merged the PR :)
