### ISSUE TITLE
Inferring node to binary mapping from compile_commands.json

### ISSUE THREAD

**Issue by mjrogozinski** [alfaix/neotest-gtest#27]
The compile_commands.json contains information about binary names, directories and source files.
It can be used instead of manually specifying the mapping.

Everyone who uses neovim for C++ will have compile_commands.json generated anyway.

**Comment by alfaix** [comment]
Hey, unfortunately I don't think this is as easy without the build tool support. Compile commands do not have link commands, and that's what you would need to map from a file to an executable.

There's [a ticket](https://github.com/alfaix/neotest-gtest/issues/12) for integrating with build tools (likely CMake only, bazel seems to be a lot less plugin-friendly), and I'll add a hook for customization. I'll close this issue as a duplicate.
