### ISSUE TITLE
I need help configuring neotest with neotest-gtest

### ISSUE THREAD

**Issue by javierfileiv** [alfaix/neotest-gtest#30]
Hello, it's damn late where I live and the only thing that's it holding me from switching from vscode to neovim is the lack of a testing interface for GTests.

It's been a while since I search everywhere and I even posted on reddit (no one replied) and I'm wondering if someone in the website is using this plugin adapter to run GTest tests.

Could you provide me with a useful configuration please?

When I try to run a test I get always 'No test found' even if I just built my file with tests. It's not asking which file to attach to parse the test (I guess it works like that)

Well, my last bottle in the sea

Thank you very much, 
have a good one.

**Comment by alfaix** [comment]
Hello, I would need to be able to reproduce the issue to be able to help. The plugin has not been changed for a while and likely should continue to work, barring some breaking changes in `neotest` or `nio`. That makes it most likely to be a configuration issue.
Could you please paste your config for `neotest` and `neotest-gtest` here?

**Comment by javierfileiv** [comment]
Thanks for your help!

my config using lazy.nvim is:
`neoest.lua`:

```lua
return {
  "nvim-neotest/neotest",
  dependencies = {
    "alfaix/neotest-gtest",
    "nvim-neotest/nvim-nio",
    "nvim-lua/plenary.nvim",
    "antoinemadec/FixCursorHold.nvim",
    "nvim-treesitter/nvim-treesitter",
  },
  opts = {
    adapters = {
      ["neotest-gtest"] = {},
      debug_adapter = "codelldb",
    },
  },
  keys = {
    { "<leader>ta", "<cmd>lua require('neotest').run.attach()<cr>", desc = "Attach to the nearest test" },
    { "<leader>tl", "<cmd>lua require('neotest').run.run_last()<cr>", desc = "Toggle Test Summary" },
    { "<leader>to", "<cmd>lua require('neotest').output_panel.toggle()<cr>", desc = "Toggle Test Output Panel" },
    { "<leader>tp", "<cmd>lua require('neotest').run.stop()<cr>", desc = "Stop the nearest test" },
    { "<leader>ts", "<cmd>lua require('neotest').summary.toggle()<cr>", desc = "Toggle Test Summary" },
    { "<leader>tt", "<cmd>lua require('neotest').run.run()<cr>", desc = "Run the nearest test" },
    {
      "<leader>tT",
      "<cmd>lua require('neotest').run.run(vim.fn.expand('%'))<cr>",
      desc = "Run test the current file",
    },
    {
      "<leader>td",
      function()
        require("neotest").run.run({ suite = false, strategy = "dap" })
      end,
      desc = "Debug nearest test",
    },
  },
}
```

`neotest-gtest.lua`:
```lua
return {
  "alfaix/neotest-gtest",
  opts = {},
}
```

**Comment by alfaix** [comment]
It looks like you're using [lazy the neovim distribution](https://www.lazyvim.org/), and not [lazy the package manager ](https://github.com/folke/lazy.nvim). Their configuration may be a little different and may require some extra magic to make friends with different adapters. See [this comment](https://github.com/alfaix/neotest-gtest/issues/6#issuecomment-2239227215) for more details.

More generally, the resulting config should look like this:
```lua
require"neotest".setup({
  -- ...
  adapters = {require"neotest-gtest", ...other adapters}
})
```
Key difference being that `adapters` is not a dict, it's a list, as per [neotest documentation](https://github.com/nvim-neotest/neotest?tab=readme-ov-file#configuration). You'll have to go through your config and understand how the config you supply in `neotest.lua` transforms into the final config and make changes based on that.

**Comment by javierfileiv** [comment]
Thanks a lot, I'm quite new to lua and nvim... do you know how I can debug that? some tutorial to see how my config finally is being transformed?

**Comment by alfaix** [comment]
Once it's loaded you can try `:lua =require"neotest.config".adapters` to see what that's been rendered to.
In general, debugging lua for me usually involves going through the source code and verifying assumptions (typically through `lua =<something>`). You can see that the config is exposed via [this module](https://github.com/nvim-neotest/neotest/blob/master/lua/neotest/config/init.lua) in `neotest`, which is where you can read it from. You should expect to see a list of identical tables (with [this interface](https://github.com/nvim-neotest/neotest/blob/master/lua/neotest/adapters/interface.lua) as its keys)

Lua is quite a simple and concise language, I think [this page](https://learnxinyminutes.com/docs/lua/) explains enough so you can read it, you can also read `:help lua-guide`, `:help neotest`, `:help lazy.nvim` which should help you understand how the config is transformed from your source files.

**Comment by javierfileiv** [comment]
That's a hell of a help! Thank you very much, will keep you posted

**Comment by javierfileiv** [comment]
I can see they saw an issue and should be fix it now. Thank you!

https://github.com/LazyVim/LazyVim/issues/4538
