### ISSUE TITLE
how to change an executable

### ISSUE THREAD

**Issue by findNextStep** [alfaix/neotest-gtest#4]
In roadmap, I see the Better support for choosing which executable to run: allow changing an executable mark as true

but I don`t see how to set or change executable in readme

I have a cpp projcet with multiple gtest executable files (for third party) and I really need this feature🙏🏻

**Comment by alfaix** [comment]
Hi,

Thanks for reaching out! Yes, the documentation is very much lacking and the main way to find things is to read the source code - sorry about that.

Currently whenever you try to run a file/test, it should prompt you for the path to the executable. You will then be prompted to edit the paths that the executable "owns", and all paths listed (recursively, if includes directories) should then be ran using that executable.
If you then run a path that is not "owned" by any executable, it will prompt you again and you can either select an existing one or create a new one. These values are cached under `stdpath("data") .. "/neotest-gtest"`. 

This is what's supposed to happen anyway - if that doesn't work, you'll need to be more specific :)

**Comment by alfaix** [comment]
If you're trying to run more than one file at a time, then you're probably running into [this](https://github.com/alfaix/neotest-gtest/blob/main/lua/neotest-gtest/init.lua#L92)
As said in the comment, there is no simple solution to it - although if it belongs to one runner, it should be relatively simple.
If you're willing to submit a PR - that'd be great, if not - I'll try to get to this next time I have some time.

**Comment by alfaix** [comment]
Hi, I clarified the roadmap a bit to also include this issue. For now I'll close it as a duplicate, feel free to reopen if what I described is not the issue you're experiencing.
