### ISSUE TITLE
Other test adapters fail to work when using gtest adapter

### ISSUE THREAD

**Issue by ErezAmihud** [alfaix/neotest-gtest#6]
Hi, When I use the gtest adapter, other adapters that I have just stop working (i.e. python adapter)

I suspect it is related to neotest version. What version do you use?
thanks

**Comment by ErezAmihud** [comment]
Nevermind, it was a problem with order of calls to setup.

I use lazy.nvim, and apparently I should have called setup in the config part of neotest

**Comment by meicale** [comment]
> Nevermind, it was a problem with order of calls to setup.
> 
> I use lazy.nvim, and apparently I should have called setup in the config part of neotest

Hi, I encounter  the same problem and would you mind sharing your answer dealing with this problem? I am using lazyvim and using neotest-python as well. I tried several order in the apdapters. How to setup that? Thank you so much!

**Comment by alfaix** [comment]
Hey @meicale I can try to help, but I need to see your configuration of neotest, neotest-gtest, neotest-python, as well as the exact behavior you observe. Could you please share that, your `neovim --version`, and make sure that all of the plugins are on current master (`:Lazy update`)?

**Comment by alfaix** [comment]
I see. I might be missing something but the configuration seems incorrect.
From [neotest documentation](https://github.com/nvim-neotest/neotest?tab=readme-ov-file#configuration), `adapters` needs to be a list:
```
require("neotest").setup({
  adapters = {
    require("neotest-python")({
      dap = { justMyCode = false },
    }),
    require("neotest-plenary"),
    require("neotest-vim-test")({
      ignore_file_types = { "python", "vim", "lua" },
    }),
  },
})
```

While upon merging your configuration, lazy will produce something like:
```
adapters = {
  ["neotest-gtest"] = {setup = {}},
  ["neotest-python"] = {dap = {justMyCode = false}},
}
```

You can change it to be a list by setting `adapters = {require("adapter-for-this-language").setup({opts})}`, though I'm also not sure if `lazy` will merge lists correctly and not just overwrite by key (which in both cases would be `1`).

If this helps, I organize my config like so:
```
-- in cpp.lua
{
  "alfaix/neotest-gtest",
  opts = {...} -- your config
}
-- in test.lua
{
  `neotest/neotest`,
  config = function()
    require"neotest".setup({
      adapters = {require"neotest-gtest", require"neotest-python"}, -- ...
    })
  end,
}
```

Then `lazy` will take care of doing `.setup(opts)` for adapters upon `require`.

**Comment by meicale** [comment]
I tried to use the similar method
