### ISSUE TITLE
How to properly set up the plugin?

### ISSUE THREAD

**Issue by ErezAmihud** [alfaix/neotest-gtest#7]
Hello, I tried to install the plugin. Running `:Neotest summery` shows me the correct files, but when entering to the file and running `require('neotest').run.run()` it alerts `No Tests Found`

I am testing it in the project in the tests/integration.

**Comment by llllvvuu** [comment]
This plugin has not adapted to breaking changes, so I made a few PRs here:

https://github.com/alfaix/neotest-gtest/pull/8
https://github.com/alfaix/neotest-gtest/pull/9

**Comment by alfaix** [comment]
Should be fixed with #8 . Please re-open if it's not.
